Fix some local bugs

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -21,7 +21,6 @@ export PATH="/usr/local/opt/python/libexec/bin:$PATH" # wtf brew
 export CLICOLOR=1
 export LSCOLORS="Exfxcxdxbxegedabagacad"
 export EDITOR="vim"
-export ANSIBLE_HOSTS="/usr/local/etc/ansible/hosts"
 export LC_ALL="en_US.UTF-8"
 export GREP_OPTIONS='--color=auto'
 
@@ -56,16 +55,16 @@ source $(which virtualenvwrapper_lazy.sh);
 
 up() { local p= i=${1:-1}; while (( i-- )); do p+=../; done; cd "$p$2" && pwd; }
 
-ssh() {
-    if ! [ -x "$(command -v mosh)" ]; then
-        echo "mosh client not found."
-        command ssh "$@"
-    else
-        echo "Found mosh client."
-        command mosh "$@"
-        [[ $? -ne 0 ]] && (echo "mosh server not found" ; command ssh "$@")
-    fi
-}
+# ssh() {
+#     if ! [ -x "$(command -v mosh)" ]; then
+#         echo "mosh client not found."
+#         command ssh "$@"
+#     else
+#         echo "Found mosh client."
+#         command mosh "$@"
+#         [[ $? -ne 0 ]] && (echo "mosh server not found" ; command ssh "$@")
+#     fi
+# }
 
 zipfix() {
     # Remove commit hashes from git archives
